<a href="https://colab.research.google.com/github/StranGer-48/Data-Analysis/blob/main/NumPyTutorial_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# **Creating a NumPy Array**

NumPy arrays are very easy to create given the complex problems they solve. To create a very basic array ndarray, you use the [np.array()](https://numpy.org/doc/stable/reference/generated/numpy.array.html) method. All you have to pass are the values of the array as a list:

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

This array contains integer values. You can specify the type of data in the dtype argument:

In [4]:
np.array([1,2,3,4],dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

Since NumPy arrays can contain only homogeneous datatypes, values will be upcast if the types do not match:

In [5]:
np.array([1,2.0,3,4])

array([1., 2., 3., 4.])

NumPy arrays can be multi-dimentional values too.

In [6]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Her we created a 2-dimensional array of values.

*Note: A matrix is just a rectangular array of numbers with shape N x M where N is the number od rows and M is the number of columns in the matrix. The one you just saw above is a 2 x 4 matrix.*

**Array of zeros**

NumPy lets you create an array of all zeros using the [np.zeros()](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html#numpy.zeros) method. All you have to do is pass the shape of the desired array:

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

The one above is a 1-D array while the one below is a 2-d array:

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

**Array of ones**

You could also create an array of all 1s using the [np.ones()](https://numpy.org/doc/stable/reference/generated/numpy.ones.html#numpy.ones) method:

In [9]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [10]:
np.ones((2,3), dtype=np.float32)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

**Random numbers in ndarrays**

Another very commonly used method to create ndarays is [np.random.rand()](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.rand.html) method. It creates an array of a given shape with random values from [0,1):

In [11]:
np.random.rand(2,3)

array([[0.75815368, 0.30156185, 0.31021497],
       [0.73651711, 0.41747322, 0.17371312]])

**An array of your choice**

Or, in fact, you can create an array filled with any given value using the [np.fill()](https://numpy.org/doc/stable/reference/generated/numpy.full.html) method. Just pass in the shape of the desired array and the value you want:

In [12]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

**Imatrix in NumPy**

Another great method is [np.eye()](https://numpy.org/doc/stable/reference/generated/numpy.eye.html) that returns an array with 1s along its diagonal and 0s everywhere else. Below is an idendtity matrix of shape 3x3.

*Note: A square matirix has an NxN shape. This means it has the same number of rows and columns.*

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

However, NumPy gives you the flexibility to change the diagonal along which the values have to be 1s. You can either move it above the main  diagonal:


In [17]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

Or move it below the main diagonal:


In [18]:
np.eye(3,k=-2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

**Evenly spaced ndarray**

You can quickly get an evenly spaced array of numbers using the [np.arange()](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)  method:

In [19]:
np.arange(5)

array([0, 1, 2, 3, 4])

The start, end and step size of the interval of values can be explicitly defined by passing in three numbers as arguments for these values respectively. A point to be here is that the interval is defined as [start,end) where the last number will not be included in the array:


In [20]:
np.arange(2,10,2)

array([2, 4, 6, 8])

Another similar funtion is [np.linspace()](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html), but instead od step size, it takes in the number of samples that need to be retrieved from the interval. A point note here is that the last number is included in the values returned unlike in the case of np.arange().


In [21]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**The Shape and Reshaping of NumPy Arrays**

Once you have created your ndarray, the next thigng you would want to do is check the number of axes, shape and the size of the ndarray.


**Dimentions of NumPy arrays**

You can easily determine the number of dimentions or axes of a NumPy array using the ndims attribute:
 

In [22]:
a = np.array([[5,10,15],[20,25,20]])
print('Array :','\n', a)
print('Dimentions :','\n',a.ndim)

Array : 
 [[ 5 10 15]
 [20 25 20]]
Dimentions : 
 2


This array has two dimentions: 2 rows and 3 columns.

**Shape of NumPy array**

The shape is an attrrie of the NumPy array that shows how many rows of elements are there along each dimention. You can further index the shape so returned by the ndarray to get value along each dimension:

In [25]:
a = np.array([[1,2,3],[4,5,6]])
print('Array :','\n',a)
print('Shape :','\n', a.shape)
print('Rows :','\n',a.shape[0])
print('Columns :', '\n', a.shape[1])

Array : 
 [[1 2 3]
 [4 5 6]]
Shape : 
 (2, 3)
Rows : 
 2
Columns : 
 3


**Size of NumPy array**

You can determine how many values there are in the array using the size attribute. It just multiplies the number of rows by the number of columns in the ndarray:


In [27]:
a = np.array([[5,10,15],[20,25,20]])
print('Size of array :',a.size)
print('Manual determination of size of array :', a.shape[0]*a.shape[1])

Size of array : 6
Manual determination of size of array : 6


**Reshaping a NumPy array**

Reshaping a ndarray can be done using the [np.reshape()](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy.reshape) method. It changes the shape of the ndarray without changing the data within the ndarray:

In [28]:
a = np.array([3,6,9,12])
np.reshape(a,(2,2))

array([[ 3,  6],
       [ 9, 12]])

Here, I reshaped the ndarray from a 1-D to a 2-D ndarray.

While reshaping, if ypu are unsure about the shape of any of the axis, just input -1. NumPy automatically calculates the shape when it sees a -1:


In [32]:
a = np.array([3,6,9,12,18,24])
print('Three rows :', '\n',np.reshape(a,(3,-1)))
print('Three columns: ','\n',np.reshape(a,(-1,3)))

Three rows : 
 [[ 3  6]
 [ 9 12]
 [18 24]]
Three columns:  
 [[ 3  6  9]
 [12 18 24]]


**Flattening a NumPy array**

Sometimes when you have a multidimentional array and want to collapse it to a single-dimentional array, you can either use the [flatten()](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten) methos or [np.ravel()](https://numpy.org/doc/stable/reference/generated/numpy.ravel.html#numpy.ravel) method:

In [33]:
a = np.ones((2,2))
b = a.flatten()
c = np.ravel(a)

print('Original shape :', a.shape)
print('Array :','\n', a)
print('Shape after flatten :', b.shape)
print('Array :','\n',b)
print('Shape after ravel :', c.shape)
print('Array :' ,'\n',c)

Original shape : (2, 2)
Array : 
 [[1. 1.]
 [1. 1.]]
Shape after flatten : (4,)
Array : 
 [1. 1. 1. 1.]
Shape after ravel : (4,)
Array : 
 [1. 1. 1. 1.]


But an important difference between flatten() and ravel() is that the former returns a copy of the original array. This means any changes made to the array returned from ravel() will also be reflected in the original array whilw this will not be the case with flatten().

In [34]:
b[0] = 0
print(a)

[[1. 1.]
 [1. 1.]]


In [35]:
c[0] = 0
print(a)

[[0. 1.]
 [1. 1.]]


But here, the changed value is also reflected in the original ndarray.

What is happening here is that flatten() creates a **Deep copy** of the ndarry while ravel() creates a **Shallow copy** of the ndarray.

Deep copy means that a completely new ndarray is created in memory and the ndarray object returned by flatten() is now pointing ti this memory location. Therefore, any changes made here will not be reflected in the original ndarray.

A Shallow copy, on the other hand, returns a reference to the original memory location. Meaning the object returned by revel() in pointing to the same memory location as the original ndarray object. So, definitely, any changes made to this ndarry will also be reflected in the original ndarray too.

**Transpose of a NumPy array**

Another very interesting reshaping method of NumPy is the [transpose()](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html#numpy.transpose) method. It takes the input array and swaps the rows with the columns values, and the columns values with the values of the rows:

**Expanding and Squeezing a NumPy array**

**Expanding a Numpy Array**
You can add a new axis to an array using the [np.expand_dims()](https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html#numpy.expand_dims) method by providing the array and the axis along which to expand:

In [37]:
a = np.array([1,2,3,4])
b = np.expand_dims(a,axis=0)
c = np.expand_dims(a,axis=1)
print('Original:','\n','Shape',a.shape,'\n',a)
print('Expand along columns:','\n','Shape',b.shape,'\n',b)
print('Expand along rows:','\n','Shape',c.shape,'\n',c)

Original: 
 Shape (4,) 
 [1 2 3 4]
Expand along columns: 
 Shape (1, 4) 
 [[1 2 3 4]]
Expand along rows: 
 Shape (4, 1) 
 [[1]
 [2]
 [3]
 [4]]


**Squeezing a NumPy array**
On the other hand, if you instead want to reduce the axis of the array, use the [np.squeeze()](print('Expand along columns:','\n','Shape',b.shape,'\n',b)) method. It removes the axis that has a single entry. This means if you have created a 2 x 2 x 1 matrix, squeeze will remove the third dimension from the matrix:

In [40]:
a = np.array([[[1,2,3],[4,5,6]]])
b = np.squeeze(a)
print('Original','\n','Shape',a.shape,'\n',a)
print('Squeeze array:','\n','Shape',b.shape,'\n',b)

Original 
 Shape (1, 2, 3) 
 [[[1 2 3]
  [4 5 6]]]
Squeeze array: 
 Shape (2, 3) 
 [[1 2 3]
 [4 5 6]]
