<a href="https://colab.research.google.com/github/StranGer-48/Data-Analysis/blob/main/NumPyTutorial_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np

**Indexing and Slicing of NumPy array**

In the previous [turorial](https://github.com/StranGer-48/Data-Analysis/blob/main/NumPyTutorial_1.ipynb) we have seen how to create a NumPy array and how to play around with its shape. In this tutorial we will see how to extract specific values from the array using indexing and slicing.

**Slicing 1-D NumPy arrays**

Slicing means retrieving elements from one index to another index. All we have to do is to pass the starting and ending point in the index like this: [start:end].

However, you can even take it up a notch by passing the step-size. Well, suppose you wanted to print every other element from the array, you would define your step-size as 2, meaning get the element 2 places away from the present index.

Incorparating all this into a single index would look something like this: [start:end:step-size].

In [31]:
a = np.array([1,2,3,4,5,6])
print(a[1:5:2])

[2 4]


Notice that the last element did not get considered. This is because slicing includes the start index but excludes the end index.

If you don't specify the start or end index, it is taken as 0 or array size, respectively, as default. And the step-size by default is 1.

In [32]:
a = np.array([1,2,3,4,5,6])
print(a[:6:2])
print(a[1::2])
print(a[1:6:])

[1 3 5]
[2 4 6]
[2 3 4 5 6]


**Slicing 2-D NumPy arrays**

Mow, a 2-D array has rows and columns so it can get a little tricky to slice 2-D arrays. But once you understand it, you can slice any dimension array!

Before learning how to slice a 2-D array, let's have a look at how to retrieve an element from a 2-D array:

In [33]:
a = np.array([[1,2,3],[4,5,6]])
print(a[0,0])
print(a[1,2])
print(a[1,0])


1
6
4


Here, we provided the row value and column value to identify the element we wanted to extract. While in a 1-D array, we were only providing the column value since there was only 1 row.

So, to slice a 2-D array, you need to mention the slices for both,the row and the column:


In [34]:
a = np.array([[1,2,3],[4,5,6]])
# print first row values
print('First row values :','\n',a[0:1,:])
# with step-size for columns
print('Alternate values from first row :','\n',a[0:1,::2])
print('Second column values :','\n',a[:,1::2])
print('Arbitrary values :','\n',a[0:1,1:3])

First row values : 
 [[1 2 3]]
Alternate values from first row : 
 [[1 3]]
Second column values : 
 [[2]
 [5]]
Arbitrary values : 
 [[2 3]]


So far we haven't seen a 3-D array. Let's first visualize how a 3-D array looks like:


In [35]:
a = np.array([[[1,2],[3,4],[5,6]],
              [[7,8],[9,10],[11,12]],
              [[13,14],[15,16],[17,18]]])
print(a)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In additon to the row and

 columns, as in 2-D array, a 3-D array also has a depth axis where it stacks one 2-D array behind the other. So, when you are slicing a 3-D array, you also need to mention which 2-D array you are slicing. This usually comes as the first value in the index:

In [36]:
print('First array, first row, first column value :', '\n',a[0,0,0])
print('First array last column :','\n',a[0,:,1])
print('First two rows for second and third arrays :','\n',a[1:,0:2,0:2])

First array, first row, first column value : 
 1
First array last column : 
 [2 4 6]
First two rows for second and third arrays : 
 [[[ 7  8]
  [ 9 10]]

 [[13 14]
  [15 16]]]


If in case you wanted the values as a single dimention array, you can always use the flatten() method to do the job!


In [37]:
print('Printing as a single array :','\n',a[1:,0:2,0:2].flatten())

Printing as a single array : 
 [ 7  8  9 10 13 14 15 16]


**Negative slicing of NumPy arrays**

An interesting way to slice your array is to use negative slicing. Negative slicing prints elements from the end rather than the beginning. Have a look below:


In [38]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[:,-1])

[ 5 10]


Here, the last values for each row were printed. If, however, we wanted to extract from the end, we would have to explicitly provide a negative step-size otherwise the result would be an empty list.

In [39]:
print(a[:,-1:-3:-1])

[[ 5  4]
 [10  9]]


An intersting use of negative slicing is to reverse the original array.

In [40]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array :','\n',a[::-1,::-1])

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array : 
 [[10  9  8  7  6]
 [ 5  4  3  2  1]]


You can also use the [np.flip()](https://numpy.org/doc/stable/reference/generated/numpy.flip.html#numpy.flip) method to reverse an ndarray.

In [41]:
a = np.array([[1,2,3,4,5],
[6,7,8,9,10]])
print('Original array :','\n',a)
print('Reversed array vertically :','\n',np.flip(a,axis=1))
print('Reversed array horizontally :','\n',np.flip(a,axis=0))

Original array : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Reversed array vertically : 
 [[ 5  4  3  2  1]
 [10  9  8  7  6]]
Reversed array horizontally : 
 [[ 6  7  8  9 10]
 [ 1  2  3  4  5]]


**Stacking and Concatenating NumPy arrays**

**Stacking ndarrays**

You can create a new array by combining existing arrays. This you can do in two ways:
  * Either combine the arrays vetically (i.e. along the rows) using the [np.vstack()](https://numpy.org/doc/stable/reference/generated/numpy.vstack.html#numpy.vstack) method, thereby incresing the number of rows in the resulting array
  * Or combine the arrays in a horizontal fashion (i.e. along the columns) using the [np.hstack()](https://numpy.org/doc/stable/reference/generated/numpy.hstack.html#numpy.hstack), thereby increasing the number of columns in the resulting array

In [42]:
a = np.arange(0,5)
b = np.arange(5,10)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Vertical stacking :','\n',np.vstack((a,b)))
print('Horizontal stacking :','\n',np.hstack((a,b)))

Array 1 : 
 [0 1 2 3 4]
Array 2 : 
 [5 6 7 8 9]
Vertical stacking : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Horizontal stacking : 
 [0 1 2 3 4 5 6 7 8 9]


A point to note here is that the axis along which you are combining the array should have the same size otherwise you are bound to ger an error!

Another intersting way to combine arrays is using the [np.dstack()](https://numpy.org/doc/stable/reference/generated/numpy.dstack.html#numpy.dstack) method. It combine array elements index by index and stacks them along the depth axis:

In [43]:
a = [[1,2],[3,4]]
b = [[5,6],[7,8]]
c = np.dstack((a,b))
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Dstack :','\n',c)
print(c.shape)

Array 1 : 
 [[1, 2], [3, 4]]
Array 2 : 
 [[5, 6], [7, 8]]
Dstack : 
 [[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]
(2, 2, 2)


**Concatenating ndarrays**

While stacking arrays is one way of combining old arrays to ger a new one, you could also use the [np.concatenate()](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html#numpy.concatenate) method where the passed arrays are joined along an existing axis:

In [44]:
a = np.arange(0,5).reshape(1,5)
b = np.arange(5,10).reshape(1,5)
print('Array 1 :','\n',a)
print('Array 2 :','\n',b)
print('Concatenate along rows :','\n',np.concatenate((a,b),axis=0))
print('Concatenate along columns :','\n',np.concatenate((a,b),axis=1))

Array 1 : 
 [[0 1 2 3 4]]
Array 2 : 
 [[5 6 7 8 9]]
Concatenate along rows : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Concatenate along columns : 
 [[0 1 2 3 4 5 6 7 8 9]]


The drawback of this method is that the original array must have the axis along which you want to combine. Otherwise, get ready to greeted by an error.

Another very useful function is to [np.append()](https://numpy.org/doc/stable/reference/generated/numpy.append.html#numpy.append) method that adds new elements to the end of a ndarray. This is obviously useful when you already have an existing ndarray but want to add new values to it.


In [45]:
a = np.array([[1,2],
              [3,4]])
np.append(a,[[5,6]],axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

 **Broadcasting in NumPy arrays - A class apart**

 Broadcasting is one of the best feature of ndarrays. It lets you perform arithmetics operations between ndarrays of different sized or between an ndarray and a simple number!

 Broadcasting essentially strtches the smaller ndarray so that it matches the shape of the larger ndarray:

In [46]:
a = np.arange(10,20,2)
b = np.array([[2],[2]])
print('Adding two different sized arrays:','\n',a+b)
print('Multiplying an ndarray and a number:','\n',a*2)

Adding two different sized arrays: 
 [[12 14 16 18 20]
 [12 14 16 18 20]]
Multiplying an ndarray and a number: 
 [20 24 28 32 36]


Its working can be thought of like stretching or making copies of the scalar, the number, [2,2,2] to match the shape of the ndarray and then perform the operation element-wise. But no such copies are being made. It is just a way of thinking avout how broadcasting is working.

This is very useful because it is more efficient to multiply an array with a scalar value rather than another array! It is important to note that two ndarrays can broadcast together only when they are compatible.



Ndarrays are compatible when:
  1. Both have the same dimensions
  2. Either of the ndarrays has a dimension of 1. The one having a dimension of 1 is broadcast to meet the size requirements of the larger ndarray.


In [47]:
a = np.ones((3,3))
b = np.array([2])
a+b

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

**NumPy Ufuncs - The secret of its sucess!**

Python is a dynamically typed language. This means the data type of a variable does not need to be known at the time of the assignment. Python will automatically determine it at run-time. While this means a cleaner and easier code to write, it also makes Pyhton sluggish.

This problem manifests itself when Python has to do many operations repeatedly, like the addition of two arrays. This is so because each time an operation need to be performed, Python has to check the data type of the element. This problem is overcome by NymPy using the **ufuncs** function. **ufuncs** are Universal functions in NumPy that are simply mathematical functions. They perform fast element-wise functions. They are called automatically when you are performing simple arithmetic operations on NumPy arrays because they act as wrappers for NumPy unfucs.

**Maths with NumPy arrays**

Here are some of the most important and useful operations that you will need to perform on your NumPy array.



**Basic arithmetic operations on NumPy arrays**

The basic arithmetic operations can easily be performed on NumPy arrays. The important thing to remember is that these simple arithmetics operation sybmols just to act as wrappers for NumPy ufucs.

In [53]:
a = np.arange(1,6)
b = np.arange(6,11)

print('Addition :', a+5)
print('Subtract :' ,a-5)
print('Multiply :', a*5)
print('Divide :', a/5)
print('Power :', a**2)
print('Remainder :', a%5)

Addition : [ 6  7  8  9 10]
Subtract : [-4 -3 -2 -1  0]
Multiply : [ 5 10 15 20 25]
Divide : [0.2 0.4 0.6 0.8 1. ]
Power : [ 1  4  9 16 25]
Remainder : [1 2 3 4 0]


**Mean, Median and Standard deviation**

To find the mean, median and standard deviation of a NumPY array, use the mean(),median() and std() methods:

In [54]:
a = np.arange(5,15,2)
print('Mean :', np.mean(a))
print('Median :', np.median(a))
print('Standard deviation', np.std(a))

Mean : 9.0
Median : 9.0
Standard deviation 2.8284271247461903


**Min-Max values and their indexes**

Min and Max values in an array can be easily found using the min() and max() methods:


In [56]:
a = np.array([[1,6],[4,3]])
print('Min :', np.min(a,axis=0))
print('Max :', np.max(a,axis=1))

Min : [1 3]
Max : [6 4]


You can also easily determin the index of the minimum or maximum value in the ndarray along a particular axis using the argmin() and argmax() methods:


In [57]:
a = np.array([[1,6,5],
[4,3,7]])
# minimum along a column
print('Min :',np.argmin(a,axis=0))
# maximum along a row
print('Max :',np.argmax(a,axis=1))

Min : [0 1 0]
Max : [1 2]
